export enum SchoolStatus {
  TRIAL = 'TRIAL',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  EXPIRED = 'EXPIRED',
  ARCHIVED = 'ARCHIVED',
}

export enum SubscriptionStatus {
  TRIAL = 'TRIAL',
  ACTIVE = 'ACTIVE',
  PAST_DUE = 'PAST_DUE',
  SUSPENDED = 'SUSPENDED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum TripStatus {
  SCHEDULED = 'SCHEDULED',
  READY = 'READY',
  STARTED = 'STARTED',
  PAUSED = 'PAUSED',
  ARRIVED_AT_SCHOOL = 'ARRIVED_AT_SCHOOL',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum StudentTripStatus {
  WAITING = 'WAITING',
  BOARDED = 'BOARDED',
  ABSENT = 'ABSENT',
  EXCUSED_ABSENCE = 'EXCUSED_ABSENCE',
  ARRIVED_AT_SCHOOL = 'ARRIVED_AT_SCHOOL',
  BOARDED_RETURN = 'BOARDED_RETURN',
  ON_BUS = 'ON_BUS',
  DROPPED_OFF = 'DROPPED_OFF',
  DELIVERY_FAILED = 'DELIVERY_FAILED',
}

export enum AddressRequestStatus {
  NEW = 'NEW',
  UNDER_REVIEW = 'UNDER_REVIEW',
  NEEDS_CHANGES = 'NEEDS_CHANGES',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SCHEDULED = 'SCHEDULED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum SyncStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SYNCED = 'SYNCED',
  FAILED = 'FAILED',
  CONFLICT = 'CONFLICT',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
  EXEMPT = 'EXEMPT',
  CANCELLED = 'CANCELLED',
}

export enum PlatformRoleEnum {
  PLATFORM_OWNER = 'PLATFORM_OWNER',
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  PLATFORM_SUPPORT = 'PLATFORM_SUPPORT',
  PLATFORM_ACCOUNTANT = 'PLATFORM_ACCOUNTANT',
}

export enum SchoolRoleEnum {
  SCHOOL_OWNER = 'SCHOOL_OWNER',
  SCHOOL_ADMIN = 'SCHOOL_ADMIN',
  TRANSPORT_MANAGER = 'TRANSPORT_MANAGER',
  ACCOUNTANT = 'ACCOUNTANT',
  SUPERVISOR = 'SUPERVISOR',
  DRIVER = 'DRIVER',
  PARENT = 'PARENT',
  DATA_ENTRY = 'DATA_ENTRY',
}

export type UserRole = PlatformRoleEnum | SchoolRoleEnum;

export enum LocationType {
  HOME = 'HOME',
  PICKUP = 'PICKUP',
  DROPOFF = 'DROPOFF',
  CUSTOM = 'CUSTOM',
  TEMPORARY = 'TEMPORARY',
}

export enum TripType {
  MORNING = 'MORNING',
  RETURN = 'RETURN',
}

export enum AbsenceType {
  MORNING_ONLY = 'MORNING_ONLY',
  RETURN_ONLY = 'RETURN_ONLY',
  FULL_DAY = 'FULL_DAY',
  MULTIPLE_DAYS = 'MULTIPLE_DAYS',
  PARENT_PICKUP = 'PARENT_PICKUP',
}

export enum TransportSubscriptionType {
  MORNING_ONLY = 'MORNING_ONLY',
  RETURN_ONLY = 'RETURN_ONLY',
  ROUND_TRIP = 'ROUND_TRIP',
  MONTHLY = 'MONTHLY',
  TERM = 'TERM',
  YEARLY = 'YEARLY',
}

export enum NotificationType {
  TRIP_STARTED = 'TRIP_STARTED',
  BUS_APPROACHING = 'BUS_APPROACHING',
  STUDENT_BOARDED = 'STUDENT_BOARDED',
  STUDENT_ABSENT = 'STUDENT_ABSENT',
}

export enum AuditAction {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  SUSPEND = 'SUSPEND',
  ACTIVATE = 'ACTIVATE',
}

export enum TicketStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  WAITING_RESPONSE = 'WAITING_RESPONSE',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
  REOPENED = 'REOPENED',
}

export enum TicketPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum InvoiceStatus {
  DRAFT = 'DRAFT',
  ISSUED = 'ISSUED',
  PAID = 'PAID',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED',
}

export enum DeviceType {
  IOS = 'IOS',
  ANDROID = 'ANDROID',
  WEB = 'WEB',
}

export enum GPSSource {
  DRIVER_PHONE = 'DRIVER_PHONE',
  SUPERVISOR_PHONE = 'SUPERVISOR_PHONE',
  EXTERNAL_DEVICE = 'EXTERNAL_DEVICE',
}
