import { ApiProperty } from '@nestjs/swagger';
import { IsArray, IsEnum, IsNotEmpty, IsString, IsUUID, ValidateNested, ArrayMaxSize } from 'class-validator';
import { Type } from 'class-transformer';

export enum SyncEventType {
  BOARDED = 'BOARDED',
  NO_SHOW = 'NO_SHOW',
  ARRIVED_AT_SCHOOL = 'ARRIVED_AT_SCHOOL',
  BOARDED_RETURN = 'BOARDED_RETURN',
  DROPPED_OFF = 'DROPPED_OFF'
}

export class SyncEventDto {
  @ApiProperty({ description: 'UUID generated by the mobile client to prevent duplicates', example: 'a1b2c3d4-e5f6-7890-abcd-1234567890ab' })
  @IsUUID()
  @IsNotEmpty()
  clientEventId: string;

  @ApiProperty({ description: 'ID of the trip being synced', example: 'trip-123' })
  @IsString()
  @IsNotEmpty()
  tripId: string;

  @ApiProperty({ description: 'ID of the student' })
  @IsString()
  @IsNotEmpty()
  studentId: string;

  @ApiProperty({ description: 'The operational event', enum: SyncEventType })
  @IsEnum(SyncEventType)
  @IsNotEmpty()
  status: SyncEventType;
  
  @ApiProperty({ description: 'ISO string of when the event happened locally' })
  @IsString()
  @IsNotEmpty()
  timestamp: string;
}

export class TripSyncBatchDto {
  @ApiProperty({ type: [SyncEventDto] })
  @IsArray()
  @ArrayMaxSize(200)
  @ValidateNested({ each: true })
  @Type(() => SyncEventDto)
  events: SyncEventDto[];
}
